### ISSUE TITLE
create "submit" command

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/topcoder-cli#16]
create a `submit` command to execute submission action. This is to prepare for the addition of other actions. command form would be `tc submit`

**Comment by sharathkumaranbu** [comment]
Since `tc` keyword is reserved by network utility in Linux, as discussed, it will be `topcoder submit`

**Comment by sharathkumaranbu** [comment]
Taken care with bug fixes in https://github.com/topcoder-platform/topcoder-cli/commit/1296972bcaac1e3e3f0c73cf0c049d2294cf5f34
