### ISSUE TITLE
Create "config" command

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/topcoder-cli#17]
Create a `config` command that will allow setting global configs for the user's username/password.

This will work similarly to how `git` is storing the configs.

If an rc file is present, it will overwrite the globally configured settings.

**Comment by sharathkumaranbu** [comment]
Added `--unset` command which will remove the key from the configuration. Also, reading of global config file was not done earlier, it is implemented now.

**Comment by sharathkumaranbu** [comment]
Implemented in https://github.com/topcoder-platform/topcoder-cli/commit/1296972bcaac1e3e3f0c73cf0c049d2294cf5f34
