### ISSUE TITLE
M2M Support

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/topcoder-cli#19]
Add in support for M2M authentication. instead of user and passwords in the rc file, support client id and secret values.

**Comment by ThomasKranitsas** [comment]
Use this library https://github.com/appirio-tech/tc-core-library-js/releases/tag/v2.6.3 for M2M. Please note that you need to refer to it via git instead of npm.

**Comment by sharathkumaranbu** [comment]
Implemented in https://github.com/topcoder-platform/topcoder-cli/commit/c1a95e671f865587349a53b451512be0101f532a

We will use the M2M capability provided by Submission API wrapper. In future when we implement commands not related to Submission API wrapper directly, we can use this library at that point of time.
