### ISSUE TITLE
pull artifacts

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/topcoder-cli#22]
- download submission artifacts to the local via command `fetch-artifacts`
- required submission Id param 
- pull all submission artifacts available to the user

**Comment by sharathkumaranbu** [comment]
We need to support the parameter `--legacySubmissionId` as well. `submissionId` and `legacySubmissionId` both are mutually exclusive.

If we have submissionId, we can directly access the submission artifacts at `https://api.topcoder-dev.com/v5/submissions/:submissionId/artifacts` and iterate through it to download the artifacts

If we have legacysubmissionId, we need to first get the submissionId from listing query like `https://api.topcoder-dev.com/v5/submissions?legacySubmissionId=:legacySubmissionId` and then follow the steps mentioned above.

Please refer to Submission API routes [here](https://github.com/topcoder-platform/submissions-api/blob/develop/src/routes/SubmissionRoutes.js)

**Comment by sharathkumaranbu** [comment]
Implemented in https://github.com/topcoder-platform/topcoder-cli/commit/c1a95e671f865587349a53b451512be0101f532a
