### ISSUE TITLE
move to submission API wrapper module

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/topcoder-cli#6]
right now the tool calls direct to the submission API. After we publish the TC submission wrapper module we should shift over to that

**Comment by cwdcwd** [comment]
@ThomasKranitsas  we now have the [submission wrapper module](https://www.npmjs.com/package/@topcoder-platform/topcoder-submission-api-wrapper) published and accepting user JWTs. Can you get this one done?

**Comment by ThomasKranitsas** [comment]
done
